//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UcusBilgileriApp.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHavayollari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHavayollari()
        {
            this.tblUcusBilgileris = new HashSet<tblUcusBilgileri>();
        }
    
        public string Id_Havayolu { get; set; }
        public string Havayolu_Adi { get; set; }
    
        public virtual tblHavayollari tblHavayollari1 { get; set; }
        public virtual tblHavayollari tblHavayollari2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUcusBilgileri> tblUcusBilgileris { get; set; }
    }
}
