//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UcusBilgileriApp.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKalkisVari
    {
        public string Id_Yer { get; set; }
        public string Yer_Adi { get; set; }
    }
}
