//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UcusBilgileriApp.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUcusBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUcusBilgileri()
        {
            this.tblYolculars = new HashSet<tblYolcular>();
        }
    
        public string Ucus_Numarasi { get; set; }
        public string Id_Havayolu { get; set; }
        public string Kalkis_Yeri_Id { get; set; }
        public string Varis_Yeri_Id { get; set; }
        public System.DateTime Kalkis_Tarih { get; set; }
        public System.TimeSpan Kalkis_Saat { get; set; }
        public System.DateTime Varis_Tarih { get; set; }
        public System.TimeSpan Varis_Saat { get; set; }
        public System.TimeSpan Tahmini_Sure { get; set; }
        public string Id_Ucak { get; set; }
    
        public virtual tblHavayollari tblHavayollari { get; set; }
        public virtual tblUcak tblUcak { get; set; }
        public virtual tblUcusBilgileri tblUcusBilgileri1 { get; set; }
        public virtual tblUcusBilgileri tblUcusBilgileri2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblYolcular> tblYolculars { get; set; }
    }
}
