USE [master]
GO

/****** Object:  Database [DtbUcus]    Script Date: 24.11.2019 18:29:33 ******/
CREATE DATABASE [DtbUcus]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DtbUcus', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.LOCALHOST\MSSQL\DATA\DtbUcus.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DtbUcus_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.LOCALHOST\MSSQL\DATA\DtbUcus_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DtbUcus].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DtbUcus] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DtbUcus] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DtbUcus] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DtbUcus] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DtbUcus] SET ARITHABORT OFF 
GO

ALTER DATABASE [DtbUcus] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DtbUcus] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DtbUcus] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DtbUcus] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DtbUcus] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DtbUcus] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DtbUcus] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DtbUcus] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DtbUcus] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DtbUcus] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DtbUcus] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DtbUcus] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DtbUcus] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DtbUcus] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DtbUcus] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DtbUcus] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DtbUcus] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DtbUcus] SET RECOVERY FULL 
GO

ALTER DATABASE [DtbUcus] SET  MULTI_USER 
GO

ALTER DATABASE [DtbUcus] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DtbUcus] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DtbUcus] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DtbUcus] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DtbUcus] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DtbUcus] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DtbUcus] SET  READ_WRITE 
GO

